# Copyright (c) 2023 Merck & Co., Inc., Rahway, NJ, USA and its affiliates.
# All rights reserved.
#
# This file is part of the aactreveal program.
#
# aactreveal is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


#' query_outcomes: Find specific outcome(s) of interest
#'
#' Function to query outcome data (outcome measurements and outcome analyses data-tables),
#' for example search for "overall survival" data.
#'
#' @inheritParams extract_aact
#' @param user_nct_ids Vector of unique NCT IDs (ex: from query_aact.R output).
#' This is only needed if outcome_measures_processsed/outcome_analyses_processed
#' are not provided (see below).
#' @param outcome_measures_processed Processed outcome measures data-set.
#' This is generated by running process_outcomes.R (not required)
#' @param outcome_analyses_processed Processed outcome analyses data-set.
#' This is generated by running process_outcomes.R (not required)
#' @param analy_study Analysis Study table
#' @param search_terms_int Intervention search terms (if searching for treatment are interest).
#' @export
#'
#' @examples
#'
#' \donttest{
#'
#' library(aactreveal)
#'
#' # Load package RDA for illustrative purposes #
#' table_names <- c("browse_interventions", "conditions", "design_group_interventions",
#' "design_groups","designs", "interventions", "outcome_analyses", "outcome_analysis_groups",
#' "outcome_measurements", "result_groups", "sponsors", "studies")
#'
#' data(list=table_names, package="aactreveal")
#'
#' # Query based on just intervention (any disease indications) #
#' terms_int <- "pembrolizumab" # Intervention / treatment
#' query_init <- query_aact(terms_int = terms_int, terms_cond = NULL)
#'
#' orr_list <- list(include = c("overall response rate", "objective response rate"),
#' exclude = c("disease control rate"),type = c("number"),range = c(0, 100) )
#' os_list <- list(include = c("overall survival"))
#' outcome_list <- list(orr_list, os_list)
#' outcome_name <- c("ORR", "OS")
#' query_out <- query_outcomes(path_raw=path_raw, user_nct_ids = query_init$user_nct_ids,
#' outcome_list = outcome_list, outcome_name = outcome_name,
#' verbose = TRUE)
#'
#' }
#'
#' @details
#'
#' The inputs for outcome querying (outcome_list) should be in the following form:
#'
#' outcome_list <- list(include = c("a"), exclude = c("b"), units= c("d"),
#'  type=c("e"), range = c(0, 100), include_param_type = c("f") )
#'
#'  Only "include" is required for the function to work. The remaining
#'  arguments will apply further restrictions.
#'
#'  "include" checks if the outcome title includes the search terms,
#'  "exclude" removes entries that include the exclusion terms,
#'  "units" searches the outcome_measurements units column,
#'  "type" searches the outcome_measurements param_type column,
#'  "range" checks whether the outcome_measurements value is within a certain range,
#'  and "include_param_type" checks the outcome_analyses param_type column.
#'
#'  To include multiple outcomes in the search, we can combine multiple lists:
#'
#' outcome_list1 <- list(include = c("a1"), exclude = c("b1"), units= c("d1"),
#'  type=c("e1"), range = c(0, 100), include_param_type = c("f") )
#'
#' outcome_list2 <- list(include = c("a2"), exclude = c("b2"), units= c("d2"),
#'  type=c("e2"), range = c(0, 125), include_param_type = c("f2") )
#'
#'  These outcomes can be assigned names through the "outcome_name" argument.
#'
#'
#'

query_outcomes <- function(con = NULL,
                           path_raw = NULL,
                           file_type=NULL,
                           board=NULL,
                           is_shiny_data = FALSE,
                           database = NULL,
                           data_preloaded = NULL,
                           user_nct_ids = NULL,
                           analy_study = NULL,
                           outcome_analyses_processed=NULL,
                           outcome_measures_processed=NULL,
                           outcome_type = NULL,
                           outcome_list = NULL,
                           outcome_name = NULL,
                           verbose = TRUE,
                           search_terms_int = NULL) {

  if (verbose) {
    message("Querying outcomes......")
  }
  # Process outcome data (unless already provided) #
  if (is.null(outcome_analyses_processed) & is.null(user_nct_ids)) {
    stop("Must provide either processed data (see process_outcomes) or vector of nct_ids")
  } else if (is.null(outcome_analyses_processed)) {

    process_outcomes_output <- process_outcomes(con = con,
                                                path_raw = path_raw,
                                                file_type = file_type,
                                                board = board,
                                                is_shiny_data = is_shiny_data,
                                                database = database,
                                                data_preloaded = data_preloaded,
                                                user_nct_ids = user_nct_ids)
    outcome_analyses_processed <- process_outcomes_output$outcome_analyses_processed
    outcome_measures_processed <- process_outcomes_output$outcome_measures_processed
  }

  if (!is.null(outcome_list)) {

    outcome_analyses_final <- outcome_analyses_processed %>%
      search_outcomes_analyses(outcome_type=outcome_type,
                               outcome_list=outcome_list,
                               outcome_name=outcome_name) #%>%
    #clean_outcomes_analyses()
    outcome_measures_final <- outcome_measures_processed %>%
      search_outcomes_measures(outcome_type=outcome_type,
                               outcome_list=outcome_list,
                               outcome_name=outcome_name) #%>%
    #clean_outcomes_measures()

  } else {
    outcome_analyses_final <- outcome_analyses_processed
    outcome_measures_final <- outcome_measures_processed
  }

  # Merge with study-level information if available #
  if (!is.null(analy_study)) {

    study_lvl_vars <- c("nct_id", "condition", "allocation", "intervention_model", "study_first_submitted_date",
                        "results_first_submitted_date", "start_date", "completion_date", "primary_completion_date",
                        "study_type", "phase", "overall_status", "enrollment", "brief_title", "official_title",
                        "number_of_arms", "sponsor_name", "sponsor_collab")
    grp_lvl_vars <- c("nct_id", "design_group_id", "group_type", "design_groups_title", "design_groups_description",
                      "mesh_term_total", "intervention_total", "intervention_num", "is_trt", "is_combo")

    analy_grp <- analy_study[,grp_lvl_vars] %>%
      mutate(design_groups_title = tolower(design_groups_title)) %>% unique()

    analy_sub <- analy_study[,study_lvl_vars] %>% unique()

    # Merge at design_group level and then at nct_id level #
    outcome_measures_final <- right_join(analy_grp, outcome_measures_final , by=c("nct_id", "design_groups_title"))
    outcome_measures_final <- right_join(analy_sub, outcome_measures_final, by="nct_id")

    outcome_analyses_final <- right_join(analy_grp, outcome_analyses_final , by=c("nct_id", "design_groups_title"))
    outcome_analyses_final <- right_join(analy_sub, outcome_analyses_final, by="nct_id")

  }
  outcome_analyses_full <- outcome_analyses_final
  # Extra check for is_trt and is_combo
  if (!is.null(search_terms_int)) {
    print("augmenting is_trt and is_combo from query_aact")
    outcome_measures_final2 <- trt_identifer(indata=outcome_measures_final,
                                            search_terms = search_terms_int,
                                            column = "design_groups_title",
                                            max_dist_lv = 1)
  }
  drop_vars <- c("design_group_id", "group_type", "design_groups_title",
                 "design_groups_description", "ctgov_group_code", "result_group_id",
                 "mesh_term_total", "intervention_total", "intervention_num",
                 "is_trt", "is_combo", "is_fuzzy_cond")
  outcome_analyses_final <- drop_cols(df=outcome_analyses_final, drop_vars) %>% unique()
  outcome_analyses_final <- trt_identifer(indata=outcome_analyses_final,
                                          search_terms = search_terms_int,
                                          column = "comp",
                                          max_dist_lv = 1)

  # Determine unique values #
  uniq_title <- unique(c(outcome_analyses_final$title,
                         outcome_measures_final$outcome_measurements_title))
  uniq_measures_param_type <- unique(outcome_measures_final$param_type)
  uniq_units <- unique(outcome_measures_final$units)
  uniq_analyses_param_type <- unique(outcome_analyses_final$param_type)

  return(list(outcome_measures_final=outcome_measures_final,
              outcome_analyses_final=outcome_analyses_final,
              uniq_title=uniq_title,
              uniq_units = uniq_units,
              uniq_measures_param_type=uniq_measures_param_type,
              uniq_analyses_param_type=uniq_analyses_param_type,
              outcome_analyses_full=outcome_analyses_full))
}



